# Generated by Django 4.2.7 on 2024-07-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places_images', verbose_name='Изображение')),
                ('category', models.ForeignKey(default='Все места', on_delete=django.db.models.deletion.CASCADE, to='places.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'db_table': 'place',
            },
        ),
    ]
