# Generated by Django 5.0.7 on 2024-08-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='description',
        ),
    ]
